### ISSUE TITLE
[Bug] required image not appear in web

### ISSUE THREAD

**Issue by greatSumini** [doobooUI-card-team/dooboo-ui#21]
**Describe the bug**
required static image source not appear

**To Reproduce**

1. run yarn web
2. go to Card

**Expected behavior**
appear properly

**Screenshots**
![Screen Shot 2020-08-22 at 2 11 15 PM](https://user-images.githubusercontent.com/48555121/90949185-59feb400-e481-11ea-9c49-612a3e2016ad.png)

**Desktop (please complete the following information):**

- OS: macOS
- Browser chrome

**Comment by sk97kang** [comment]
Please check the file path and try again.
